## Notebook Imports

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

2.1.2+cpu


## Introduction to Tensors


In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                       [3, 6, 7],
                       [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 7],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

## Random Tensors

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random number -> look at the data -> update random numbers -> look at the data -> update random numbers`

In [16]:
# Create a random tensor
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8223, 0.4365, 0.8988, 0.9544],
        [0.4772, 0.1273, 0.2887, 0.1948],
        [0.1888, 0.4558, 0.4194, 0.8409]])

In [17]:
random_tensor.ndim

2

In [18]:
# Create an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeroes and Ones

In [19]:
zeroes = torch.zeros(size=(3, 4))
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## A Range of Tensors and Tensor-Like

In [21]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
# Creating tensor like
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

 ## Tensor Datatypes

In [23]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype=None, # what datatype is the tensor (e.g float32)
                              device=None, # what device is your tensor
                              requires_grad=False) # whether or not to track gradients with these tensor operations

float_32_tensor 

tensor([3., 6., 9.])

In [24]:
float_16_tensor = float_32_tensor.type(torch.float16) # or torch.half
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

## Getting information from tensors  

In [26]:
some_tensor = torch.rand([3, 3])
print(some_tensor)
some_tensor.dtype, some_tensor.shape, some_tensor.device

tensor([[0.6736, 0.2060, 0.2299],
        [0.8878, 0.2297, 0.3718],
        [0.1272, 0.2571, 0.2774]])


(torch.float32, torch.Size([3, 3]), device(type='cpu'))

## Manipulating Tensor (tensor operations)

Tensor operations include:
* **Addition**
* **Subtraction**
* **Multiplication**
* **Division**
* **Matrix Multiplication**

In [27]:
print(f'Addition: {some_tensor + 10}') # torch.add(tensor, 10)
print(f'Subtraction: {some_tensor - 10}')
print(f'Multiplication: {some_tensor * 10}')
print(f'Division: {some_tensor / 10}')

Addition: tensor([[10.6736, 10.2060, 10.2299],
        [10.8878, 10.2297, 10.3718],
        [10.1272, 10.2571, 10.2774]])
Subtraction: tensor([[-9.3264, -9.7940, -9.7701],
        [-9.1122, -9.7703, -9.6282],
        [-9.8728, -9.7429, -9.7226]])
Multiplication: tensor([[6.7363, 2.0601, 2.2990],
        [8.8778, 2.2971, 3.7184],
        [1.2716, 2.5710, 2.7744]])
Division: tensor([[0.0674, 0.0206, 0.0230],
        [0.0888, 0.0230, 0.0372],
        [0.0127, 0.0257, 0.0277]])


In [28]:
# Element-wise Multiplication 
some_tensor * some_tensor

tensor([[0.4538, 0.0424, 0.0529],
        [0.7881, 0.0528, 0.1383],
        [0.0162, 0.0661, 0.0770]])

In [29]:
# Matrix Multiplication (dot product)
torch.matmul(some_tensor, some_tensor)

tensor([[0.6659, 0.2452, 0.2952],
        [0.8492, 0.3313, 0.3927],
        [0.3492, 0.1566, 0.2018]])

## Shape Errors

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [30]:
tensor_A = torch.tensor([[1, 2],
                       [3, 4],
                       [5, 6]])

tensor_B = torch.tensor([[7, 10],
                       [8, 11],
                       [9, 12]])

In [31]:
torch.mm(tensor_A, tensor_B.T) # or torch.matmul()

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Min, Max, Mean, Sum (Tensor Aggregation)

In [32]:
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [33]:
print(f'Torch Min: {torch.min(x)}') # or x.min()
print(f'Torch Max: {torch.max(x)}') # or x.max()
print(f'Torch Mean: {torch.mean(x.type(torch.float32))}') # or x.type(torch.float32).mean()
print(f'Torch Sum: {torch.sum(x)}') # or x.sum()

Torch Min: 0
Torch Max: 90
Torch Mean: 45.0
Torch Sum: 450


## Finding the positional Min and Max

In [34]:
print(f'Position: {x.argmin()}, Value: {x[x.argmin()]}')

Position: 0, Value: 0


In [35]:
print(f'Position: {x.argmax()}, Value: {x[x.argmax()]}')

Position: 9, Value: 90


## Reshaping, Stacking, Squeezing and Unsqueezing tensors

* **Reshaping** -- reshapes an input tensor to a defined shape
* **View** -- return a view of an input tensor of a certain shape but keep the same memory as the original tensor
* **Stacking** -- combine multiple tensors on top of each other (vstack) or side by side (hstack)
* **Squeezing** -- removes a `1` dimension from a tensor
* **Unsqueezing** -- adds a `1` dimension to a target tensor
* **Permute** -- return a view of the input with dimensions permuted (swapped) in a certain way

In [36]:
# Reshaping
print(f'Previous Tensor: {x}')
print(f'Previous Shape: {x.shape}')

x_reshaped = x.reshape(1, 10)

print(f'\nNew Tensor: {x_reshaped}')
print(f'New Shape: {x_reshaped.shape}')

Previous Tensor: tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Previous Shape: torch.Size([10])

New Tensor: tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])
New Shape: torch.Size([1, 10])


In [37]:
# Change the view
z = x.view(5, 2)
z, z.shape

(tensor([[ 0, 10],
         [20, 30],
         [40, 50],
         [60, 70],
         [80, 90]]),
 torch.Size([5, 2]))

In [38]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[ 0,  0,  0,  0],
        [10, 10, 10, 10],
        [20, 20, 20, 20],
        [30, 30, 30, 30],
        [40, 40, 40, 40],
        [50, 50, 50, 50],
        [60, 60, 60, 60],
        [70, 70, 70, 70],
        [80, 80, 80, 80],
        [90, 90, 90, 90]])

In [39]:
# Squeezing tensors
print(f'Previous Tensor: {x_reshaped}')
print(f'Previous Shape: {x_reshaped.shape}')

x_squeezed = x_reshaped.squeeze()

print(f'\nNew Tensor: {x_squeezed}')
print(f'New Shape: {x_squeezed.shape}')

Previous Tensor: tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])
Previous Shape: torch.Size([1, 10])

New Tensor: tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
New Shape: torch.Size([10])


In [40]:
# Unsqueezing tensors
print(f'Previous Tensor: {x_squeezed}')
print(f'Previous Shape: {x_squeezed.shape}')

x_unsqueezed = x_squeezed.unsqueeze(dim=0)

print(f'\nNew Tensor: {x_unsqueezed}')
print(f'New Shape: {x_unsqueezed.shape}')

Previous Tensor: tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Previous Shape: torch.Size([10])

New Tensor: tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])
New Shape: torch.Size([1, 10])


In [41]:
# Permutation
x_original = torch.rand(size=(224, 224, 3)) # height, width, colour channels

x_permuted = x_original.permute(2, 0, 1) # shift 0->1, 1->2, 2->0

print(f'Previous shape: {x_original.shape}')
print(f'New shape: {x_permuted.shape}') # colour channels, height, width

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

In [42]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [43]:
print(f'Index on the first bracket: \n{x[0]}')
print(f'\nIndex on the middle bracket: {x[0][0]}')
print(f'\nIndex on the inner bracket: {x[0, 0, 0]}')

Index on the first bracket: 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Index on the middle bracket: tensor([1, 2, 3])

Index on the inner bracket: 1


In [44]:
# ':' all of target dimension
x[:, 0], x[:, :, 2], x[:, 1, :]

(tensor([[1, 2, 3]]), tensor([[3, 6, 9]]), tensor([[4, 5, 6]]))

## Pytorch Tensors & NumPy

* Data in NumPy -> Pytorch Tensor: `torch.from_numpy(ndarray)`
* Pytorch Tensor -> NumPy: `torch.Tensor.numpy()`

In [45]:
import numpy as np

# Numpy array to Pytorch tensor 
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # pytorch reflects numpy's default datatype of float64
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [46]:
# Pytorch tensor to Numpy array
tensor = torch.ones(7)
array = tensor.numpy() 
tensor, array

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))